### ISSUE TITLE
关机不能断电是啥原因啊？

### ISSUE THREAD

**Issue by zook-sze** [hoanX/xps13-9360-Hackintosh#30]
9360,8550U，需要提供啥信息才能定位问题呢？

**Comment by zook-sze** [comment]
目前暂时性解决了，用U盘制作一个ubuntu的安装盘，然后试用，进入ubuntu桌面后，用ubuntu关机。这时候就恢复正常关机了，具体是啥原因？BIOS是2.13的…………是不是dell的bios会判断是否安装了linux/unix系统后，调整了电源管理方式？

**Comment by hoanX** [comment]
我发现好多人都遇到这个问题了，不清楚怎么引起的，这个时候Windows都有问题了，我之前也遇到了，也是和你一样的方法解决的

**Comment by zook-sze** [comment]
我觉得应该是dell笔记本的内置电源管理带来的问题，比较dell内置的电源管理真的蛮强大的，跟多数内置的电源管理是不太一样，所以应该是ubuntu启动后，dell内置的电源管理程序做了智能化匹配，比较dell的很多电脑出厂时的操作系统是ubuntu。我觉得还是原生电源补丁的问题……应该需要做进一步修正的。但具体找不到原因在哪里，oc的dsdt表也提示有53处警告，一处一处的修改完善后不知道是不是能调整过来，或者是其他的什么ACPI表的问题。

**Comment by hoanX** [comment]
上次好了后再也没出现过，我感觉是有一个版本clover或者oc引起的

**Comment by Orionecode** [comment]
天呐，我的9570也是用安装Ubuntu解决了这个问题，重装Windows，降级bios都没用，差点换主板了，谢谢你们

**Comment by Orionecode** [comment]
天呐，我的9570也是用安装Ubuntu解决了这个问题，重装Windows，降级bios都没用，差点换主板了
