### ISSUE TITLE
无法进入安装界面

### ISSUE THREAD

**Issue by Lorde627** [hoanX/xps13-9360-Hackintosh#32]
![image](https://user-images.githubusercontent.com/63381047/94668441-9ce65e00-0342-11eb-994b-532c1f6197b9.jpg)
一直处于这个状态🆘

**Comment by Lorde627** [comment]
Ifnet_attach:all kernel threads for interface lo0 have been scheduled at least once.Proceeding

**Comment by zou2699** [comment]
![image](https://user-images.githubusercontent.com/20203592/95156337-e7dff580-07c8-11eb-9ec9-537ac9af62f4.png)
开启这个试试

**Comment by Lorde627** [comment]
> ![image](https://user-images.githubusercontent.com/20203592/95156337-e7dff580-07c8-11eb-9ec9-537ac9af62f4.png)
> 开启这个试试

完美解决问题谢谢！！！
