### ISSUE TITLE
网卡更换尺寸问题

### ISSUE THREAD

**Issue by XziSun** [hoanX/xps13-9360-Hackintosh#34]
请问一下大大，直接装BCM94360cs2 的话需要用延长线吗还是直接装上去长度就ok了呀？相比dw1560这些，BCM94360cs2 加上转接卡的话不是要长那么一两厘米么？
非常感谢～

**Comment by hoanX** [comment]
需要某宝的延长线转接卡

**Comment by XziSun** [comment]
好的好的，真是太感谢了～～👍
