### ISSUE TITLE
冒昧问一下，clover转oc，需要做些什么

### ISSUE THREAD

**Issue by cdrink** [hoanX/xps13-9360-Hackintosh#36]
搜了一下，看糊涂了，现在的9360用的是hoanX的clover引导文件，为了方便后面升级到big sur，想换成oc引导，需要做些什么，除了将config文件中的机器序列号等修改成自己的之外，哪些文件要拷贝到引导盘，是拷贝到EFI文件夹中吗？感谢

**Comment by hoanX** [comment]
替换oc文件夹，还有boot，记得重置下nvram
