### ISSUE TITLE
播放视频卡顿

### ISSUE THREAD

**Issue by 451725563** [hoanX/xps13-9360-Hackintosh#37]
刚刚换上大佬的OC，现在只有一个问题了：每次播放视频都会整个系统突然卡住。不管是B站、油管、还是百度云和IINA本地播放都有这种情况。

之前用clover 5122的时候没有这种情况，然后升级到5126之后也出现了这个问题，想着也许是clover的问题换到了OC，发现现在也有这个问题。
在VideoProc中查看核显也正确驱动了：
<img width="863" alt="image" src="https://user-images.githubusercontent.com/20039197/99042265-6f3e3700-25c7-11eb-903a-31accac299a0.png">

对着Intel Power Gadget看了一下，除了发现播放视频之后核心频率和功率会升的很高（我也不知道这正不正常），没发现有什么特殊的变化：
<img width="373" alt="image" src="https://user-images.githubusercontent.com/20039197/99042028-f808a300-25c6-11eb-8e64-be2bbc29f239.png">

**Comment by 451725563** [comment]
现在发现问题不在显卡上了，主要出在蓝牙上
发现只要连着蓝牙耳机看视频就会出现卡顿的问题
应该是驱动的bug了

**Comment by hoanX** [comment]
2.4G WIFI？这个会和蓝牙干扰

**Comment by 451725563** [comment]
> 2.4G WIFI？这个会和蓝牙干扰

不是，我一直用的5G wifi，不过现在升级到BigSur之后就没有这个问题了，可能是10.15.7的bug？

**Comment by hoanX** [comment]
不清楚，我以前也没遇到
