### ISSUE TITLE
关于亮度调节的修复

### ISSUE THREAD

**Issue by kaedea** [hoanX/xps13-9360-Hackintosh#48]
我用了你的 OC 配置，屏幕亮度调整总算正常了。然而其他几个大佬的 9360 OC 配置都是亮度有问题，请问 UP 主修复亮度调整主要是哪些配置呢？（我用了你的配置屏幕会 Flickering）

**Comment by hoanX** [comment]
之前ssdt修复，后来BrightnessKeys.kext支持了，去除了之前的ssdt，闪屏问题，我目前在看b站经常遇到，其他情况基本不会，原因不详

**Comment by kaedea** [comment]
@hoanX 
你好，我通过对比测试，发现是 `OC/ACPI/SSDT-BCKM.aml` 修复了 Brightness 的问题。

除了屏幕亮度外，我的 9360 如果使用 ig-platform-id `1659`，会出现屏幕闪屏问题。如果使用`1B59` 则正常，但是 HDMI 外接显示器不工作了。经过多番调试，还是停留在这个阶段，不知道 UP 是否有遇到过。
问题视频参考：https://github.com/theQuert/XPS-9360-macOS/issues/72

**Comment by hoanX** [comment]
你这个闪屏好严重啊，我正常使用可能好几天才会遇到一次，还有就是b站播放时间

**Comment by kaedea** [comment]
@hoanX 我折腾了一周也感觉可能是 DVMT 或者 HiDP 的问题

**Comment by kaedea** [comment]
@hoanX 我发现看 B 站闪屏问题，有可能是屏幕供电不足。
