### ISSUE TITLE
有关oc启动win的修复

### ISSUE THREAD

**Issue by q240627995** [hoanX/xps13-9360-Hackintosh#50]
正常来说，只要ddst修改是符合规则的、添加了系统判断的，就能正常从oc启动win10.
我这边双系统无法正常启动win10，一开始以为是ddst补丁没加入系统判断导致不能开机，经检查发现ddst做的很好，大部分都有系统判断，所以排除。
经过不断的爬楼，找到了解决办法：打开cofig，booter-Quirks-勾选SyncRuntimePerimissions 即可（出处黑果小兵）
（仔细检查，SSDT-PTSWAK没加入系统判断（具体为啥没加看不懂就不管了），不管什么原因，最好还是bios启动win，最稳定安全）

最后想问下大佬还考虑会更新吗？您的oc文件实在是太完美了，非常感谢您的工作！

**Comment by hoanX** [comment]
目前没什么需要更新的，也就驱动和oc的日常更新，dell的bios添加引导也方便，win10我都是bios启动，Monterey出正式版可能还会更新最后一次吧

**Comment by q240627995** [comment]
确实，目前黑苹果工作非常稳定，感谢您的工作！！！
