### ISSUE TITLE
各位有 8550u 安装成功的么？

### ISSUE THREAD

**Issue by bitboxclub** [hoanX/xps13-9360-Hackintosh#52]
折腾了3天了，12 和11 都进不了引导。
Catalina 倒是能进引导。但是安装后 opencore看不到引导分区。
哪位大哥拉兄弟一把？

**Comment by libxing** [comment]
看不到u盘的安装分区是嘛 多找几个安装教程看看

**Comment by bitboxclub** [comment]
按照 https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html
走了一遍流程，配置成功了。感谢共享efi
